[package]
name = "hypescript"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.0"
pest_derive = "2.0"
insta = "1.14.0"
maplit = "1.0"
lazy_static = "1.4.0"
strum = "0.24.1"
strum_macros = "0.24.3"
